workflows:
  ios-workflow:
    name: iOS Build & Test
    environment:
      xcode: latest
      ruby: latest
      cocoapods: 1.11.3  # specify a Cocoapods version as string
      node: none
      flutter: none

    scripts:
      - name: Install dependencies
        script: |
          pod install --repo-update

      - name: Run tests
        script: xcodebuild test \
          -workspace SixtemiaTest.xcworkspace \
          -scheme SixtemiaTest \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          ONLY_ACTIVE_ARCH=NO \
          ENABLE_CODE_COVERAGE=YES

    artifacts:
      - build/ios/ipa/*.ipa
      - build/reports/tests/*.xml
