workflows:
  ios-workflow:
    name: iOS Build & Test
    environment:
      xcode: latest
      ruby: "3.2.2"

    scripts:
      - name: Install dependencies
        script: |
          echo "Installing CocoaPods 1.16.2..."
          gem install cocoapods -v 1.16.2
          pod install --repo-update

      - name: Run tests
        script: |
          xcodebuild test \
            -workspace SixtemiaTest.xcworkspace \
            -scheme SixtemiaTest \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            ONLY_ACTIVE_ARCH=NO \
            ENABLE_CODE_COVERAGE=YES

    artifacts:
      - build/ios/ipa/*.ipa
      - build/reports/tests/*.xml
